/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-03-07 05:27:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.chatbotBuilderContents;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chatbotBuilderBottomSetting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/home/minds/maum/sds-builder/apache-tomcat-8.5.99/webapps/sds-builder/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1617291808000L));
    _jspx_dependants.put("jar:file:/home/minds/maum/sds-builder/apache-tomcat-8.5.99/webapps/sds-builder/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153385082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <META HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\n");
      out.write("\n");
      out.write("    <!-- cache 지우는 meta 태그 -->\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-cache\" /> <!-- 캐시가 되지 않도록 정의 -->\n");
      out.write("    <meta http-equiv=\"Pragma\" content=\"no-cache\" /> <!-- 캐시가 되지 않도록 정의 -->\n");
      out.write("    <meta http-equiv=\"Expires\" content=\"-1\"> <!-- 즉시 캐시만료 -->\n");
      out.write("    <title>chatbot builder Setting</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<p id=\"css\">\n");
      out.write("    /* MINDsLab. UX/UI Team. AMR. 20201201 */\n");
      out.write("    #chatbot {display:block; overflow:hidden; position:fixed; width: 90px; right:0; bottom:55px; height:75px; border-radius:10px; z-index:9999;}\n");
      out.write("    #chatbot.chatOpen {width: 370px; height:80%; bottom: 0px;}\n");
      out.write("    #chatbot.aside_area {width: 725px;}\n");
      out.write("    #chatbot_iframe {position: absolute; right: 0px; bottom: 0px; width:775px;height:100%; border:none;}\n");
      out.write("    .chatGreeting:hover .btn_greetClose {opacity: 1;}\n");
      out.write("    .chatGreeting {display:block; position:fixed; right:100px; bottom:30px; margin-bottom:0px; padding:10px 35px 10px 10px; line-height: 18px; color:rgba(--main-text-rgb,1.0); font-size:12px; text-align:right; border-radius:7px; background:rgba(--main-color-rgb,1.0); z-index:700; -webkit-animation-duration:1.2s; animation-duration:1.2s; -webkit-animation-fill-mode:both; animation-fill-mode:both; -webkit-animation-name:chatGreeting; animation-name:chatGreeting; animation-delay:0.5s;}\n");
      out.write("    /* 200310 AMR animation 경량화 */\n");
      out.write("    @-webkit-keyframes chatGreeting {\n");
      out.write("    0%   {opacity:0; display:none; transform: translateY(0px);}\n");
      out.write("    50%  {opacity:0; display:none; transform: translateY(0px);}\n");
      out.write("    100% {opacity:1; display:block; transform: translateY(-30px);}\n");
      out.write("    }\n");
      out.write("    @keyframes chatGreeting {\n");
      out.write("    0%   {opacity:0; display:none; transform: translateY(0px);}\n");
      out.write("    50%  {opacity:0; display:none; transform: translateY(0px);}\n");
      out.write("    100% {opacity:1; display:block; transform: translateY(-30px);}\n");
      out.write("    }\n");
      out.write("    .chatGreeting.chatGreeting_hide {animation-delay:0s; -webkit-animation-duration:0.3s; animation-duration:0.3s; -webkit-animation-fill-mode:both; animation-fill-mode:both; -webkit-animation-name:chatGreeting_hide; animation-name:chatGreeting_hide; }\n");
      out.write("    @-webkit-keyframes chatGreeting_hide {\n");
      out.write("    0%   {opacity:1; display:block; transform: translateY(-30px);}\n");
      out.write("    100% {opacity:0; display:none; transform: translateY(0px);}\n");
      out.write("    }\n");
      out.write("    @keyframes chatGreeting_hide {\n");
      out.write("    0%   {opacity:1; display:block; transform: translateY(-30px);}\n");
      out.write("    100% {opacity:0; display:none; transform: translateY(0px);}\n");
      out.write("    }\n");
      out.write("    .powered {display:block; position:fixed; right:20px; bottom:30px; margin-bottom:0; color:#fff; font-size:12px; text-align:right; text-shadow:1px 1px 3px rgba(0, 0, 0, 0.7); z-index:700;}\n");
      out.write("    .powered img {height:9px; margin:0 0 1px 4px; vertical-align:middle;}\n");
      out.write("    #chatbot.chatOpen ~ .chatGreeting {display:none;}\n");
      out.write("    #chatbot.chatOpen ~ .powered {display:none;}\n");
      out.write("    .btn_greetClose {overflow: hidden; position:absolute; top: 10px; right: 8px; width: 20px; height: 20px; text-indent:-99px; border:none; border-radius: 50%; cursor:pointer; background-color: rgba(255,255,255,0.7); transition:all 0.3s ease-out;opacity: 0;}\n");
      out.write("    .btn_greetClose:before,\n");
      out.write("    .btn_greetClose:after {content:''; position:absolute; top:50%; left:4px; width:12px; height:1px; background:rgba(0,0,0,0.9);}\n");
      out.write("    .btn_greetClose:before {transform:rotate(-45deg);}\n");
      out.write("    .btn_greetClose:after {transform:rotate(45deg);}\n");
      out.write("    @media all and (max-width: 768px) {\n");
      out.write("    #chatbot {right:0; bottom:40px; width: 75px; height: 55px; border-radius:0; z-index:9999;}\n");
      out.write("    #chatbot #btn_goChat {bottom:0; width:55px; margin:0 10px 40px 0; padding:50px 0 0 0;}\n");
      out.write("    #chatbot.chatOpen {bottom:0px; width: 100%; height:100%;}\n");
      out.write("    .powered {bottom:12px;}\n");
      out.write("    .chatGreeting {left:auto; right: 80px; width: auto; margin-bottom: -20px; text-align:left; word-break: keep-all;}\n");
      out.write("\n");
      out.write("    #chatbot_iframe {width: 100%;}\n");
      out.write("\n");
      out.write("    .chatGreeting .btn_greetClose {opacity: 1;}\n");
      out.write("    }\n");
      out.write("    #btn_goChat {border:2px solid rgba(--main-color-rgb,1.0); background:url(\"--main-icon\") 50% 50% no-repeat; background-size:cover;}\n");
      out.write("    #chatUI_wrap .chatUI_top h1 {color:rgba(--main-color-rgb,1.0);  background: url(\"--main-logo\") no-repeat 50% 0; background-size: auto 50px;}\n");
      out.write("    #chatUI_wrap .chatUI_top h1 img {height: 50px;}\n");
      out.write("    #chatUI_wrap .chatUI_top .langBox .lst_lang li button:hover,.chatUI_top .langBox .lst_lang li button:focus {border:1px solid rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_top .langBox .lst_lang li button.active {background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk li.user .txt {background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk li.bot:first-child:before {background:rgba(--main-color-rgb,1.0) url(\"--main-icon\") 50% 50% no-repeat; background-size:cover; }\n");
      out.write("    #chatUI_wrap li.user + li.bot:before {background:#fff url(\"--main-icon\") 50% 50% no-repeat; background-size:cover;}\n");
      out.write("    #chatUI_wrap .chatLoading > em {background-color:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .txt {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .generic .generic_tit a {color:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .generic .generic_tit a:before {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .generic .generic_tit a:after {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .generic .generic_url a {color:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .generic .generic_url a:before {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .generic .generic_url a:after {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnLst ul li a {color:rgba(--main-color-rgb,1.0); }\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnLst ul li a:hover {box-shadow:rgba(--main-color-rgb,1.0) 0 80px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnLst ul li a.active {background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnLst .btnBox button.btn_point {background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnItem ul li a {color:rgba(--main-color-rgb,1.0); box-shadow:rgba(--main-color-rgb,0) 0 0px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnItem ul li a:hover {box-shadow:rgba(--main-color-rgb,1.0) 0 80px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnItem ul li a.btnStart {box-shadow:rgba(--main-color-rgb,1.0) 0 80px 0px 2px inset; background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnItem ul li a.active {background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    #chatUI_wrap li.bot_promotion:before {background: rgba(--main-color-rgb,1.0) url(\"--main-icon\") 50% 50% no-repeat; background-size: cover;}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .bot_promotion .generic .generic_tit {color: rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk li.botMsg_swiper a.swiper_item:hover {border:1px solid rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .full_preview .swiper-pagination-bullet-active {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .swiper-button-prev, .swiper-container-rtl .swiper-button-next {background:rgba(--main-color-rgb,0.9) url(\"../images/arw_left_w.png\") center center no-repeat;}\n");
      out.write("    #chatUI_wrap .swiper-button-next, .swiper-container-rtl .swiper-button-prev {background:rgba(--main-color-rgb,0.9) url(\"../images/arw_right_w.png\") center center no-repeat;}\n");
      out.write("    #chatUI_wrap .swiper-pagination-bullet-active {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .full_preview .swiper-pagination-bullets .swiper-pagination-bullet {border: 1px solid rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_btm .textArea:focus {border:1px solid rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_btm .btn_chat {background-color:rgba(--main-color-rgb,1.0);}\n");
      out.write("    .chatAside .checkBox input[type=\"checkbox\"]:checked + label:before{border-color:rgba(--main-color-rgb,1.0); background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    .chatAside .radioBox input[type=\"radio\"]:checked + label:before{border-color:rgba(--main-color-rgb,1.0); background:rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("    .chatAside .chatAside_hd h3 {color:rgba(--main-color-rgb,1.0);}\n");
      out.write("    .chatAside .chatAside_bd .btnBox button.btn_point {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    .chatAside .chatAside_bd .stnBox.popup .popup_content .ico_circle {background: rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .txt .txt_btn a {color:rgba(--main-color-rgb,1.0) !important; box-shadow:rgba(--main-color-rgb,0) 0 0px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .txt .txt_btn a:hover {border:1px solid rgba(--main-color-rgb,0) !important; box-shadow:rgba(--main-color-rgb,1.0) 0 80px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .txt .txt_btns a {color:rgba(--main-color-rgb,1.0) !important; box-shadow:rgba(--main-color-rgb,0) 0 0px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .txt .txt_btns a:hover {border:1px solid rgba(--main-color-rgb,0) !important;  box-shadow:rgba(--main-color-rgb,1.0) 0 80px 0px 2px inset;}\n");
      out.write("    #chatUI_wrap .mapWrap .mapWrap_cont .btn_mapLoad_detail {background:rgba(--main-color-rgb,1.0);}\n");
      out.write("    #chatUI_wrap .chatUI_mid .lst_talk .btnLst .txt.txt_radius {background: rgba(--main-color-rgb,1.0); color:rgba(--main-text-rgb,1.0);}\n");
      out.write("</p>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
